/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, Html } from '@react-three/drei'

function Model_BedsideCabinet(props) {
  const { nodes, materials } = useGLTF('/models/bedsideCabinet.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Cube003.geometry} material={materials.bedsideMat} />
      <mesh castShadow receiveShadow geometry={nodes.Cube003_1.geometry} material={materials['chipboardMat.001']} />

      <Html position={[1.5, .5, -2]}>
        <div className='object-html-marker' onClick={() => props.onClick('bedsideCabinet')}>
          
        </div>
      </Html>
    </group>
  )
}

useGLTF.preload('/models/bedsideCabinet.glb')

export default Model_BedsideCabinet