/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, Html } from '@react-three/drei'

function Model_Wardrobe(props) {
  const { nodes, materials } = useGLTF('/models/wardrobe.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow  geometry={nodes.Cylinder003.geometry} material={materials['lightBeigeMat.001']} />
      <mesh castShadow receiveShadow  geometry={nodes.Cylinder003_1.geometry} material={materials['handleMat.001']} />
      <mesh castShadow receiveShadow  geometry={nodes.Cylinder003_2.geometry} material={materials['chipboardMat.001']} />
    
      <Html position={[-2, 2, 1.7]}>
        <div className='object-html-marker' onClick={() => props.onClick('wardrobe')}>
          
        </div>
      </Html>
    </group>
  )
}

//useGLTF.preload('/models/wardrobe.glb')

export default Model_Wardrobe
