/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, Html } from '@react-three/drei'

function Model_Duvet(props) {
  const { nodes, materials } = useGLTF('/models/duvet.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.duvet.geometry} material={materials.duvetMat}>
        <Html position={[0, .6, -1.2]}>
            <div className='object-html-marker' onClick={() => props.onClick('duvet')}>
              
            </div>
          </Html>
      </mesh>
    </group>
  )
}

//useGLTF.preload('/models/duvet.glb')

export default Model_Duvet
