/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, Html } from '@react-three/drei'

function Model_Rug(props) {
  const { nodes, materials } = useGLTF('/models/rug.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.rug.geometry} material={materials['rugMat.001']} />
      <Html position={[-.5, .05, 1]}>
        <div className='object-html-marker' onClick={() => props.onClick('rug')}>
          
        </div>
      </Html>
    </group>
  )
}

//useGLTF.preload('/models/rug.glb')

export default Model_Rug
