/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, Html } from '@react-three/drei'

function Model_Bedframe(props) {
  const { nodes, materials } = useGLTF('/models/bedframe.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.bedframe.geometry} material={materials.bedframeMat}>
        <Html position={[0, .6, -.1]}>
          <div className='object-html-marker' onClick={() => props.onClick('bedframe')}>
            
          </div>
        </Html>
      </mesh>
    </group>
  )
}

//useGLTF.preload('/models/bedframe.glb')

export default Model_Bedframe
