/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Model_Pillows(props) {
  const { nodes, materials } = useGLTF('/models/pillows.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.pillow001.geometry} material={materials.pillowMat} />
    </group>
  )
}

//useGLTF.preload('/models/pillows.glb')

export default Model_Pillows
