/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, Html } from '@react-three/drei'

function Model_UnderbedStorage(props) {
  const { nodes, materials } = useGLTF('/models/underbedStorage.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="underBedStore" castShadow receiveShadow geometry={nodes.underBedStore.geometry} material={materials.underBedStoreMat} />
      <Html position={[1.1, .2, -.7]}>
        <div className='object-html-marker' onClick={() => props.onClick('underbedStorage')}>
          
        </div>
      </Html>
    </group>
  )
}

useGLTF.preload('/models/underbedStorage.glb')

export default Model_UnderbedStorage
