/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, Html } from '@react-three/drei'

function Model_Drawers(props) {
  const { nodes, materials } = useGLTF('/models/drawers.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Cube019.geometry} material={materials.drawersMat} />
      <mesh castShadow receiveShadow geometry={nodes.Cube019_1.geometry} material={materials.handleMat} />
      <mesh castShadow receiveShadow geometry={nodes.Cube019_2.geometry} material={materials['chipboardMat.001']} />

      <Html position={[-2, .5, .1]}>
        <div className='object-html-marker' onClick={() => props.onClick('drawers')}>
          
        </div>
      </Html>
    </group>
  )
}

useGLTF.preload('/models/drawers.glb')

export default Model_Drawers
