/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Model_Window(props) {
  const { nodes, materials } = useGLTF('/models/window.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Plane002" castShadow receiveShadow geometry={nodes.Plane002.geometry} material={materials.windowMat} />
      {/* <mesh name="Plane002_1" castShadow receiveShadow geometry={nodes.Plane002_1.geometry} material={materials.lightMat} /> */}
      <mesh name="Plane002_1" castShadow receiveShadow geometry={nodes.Plane002_1.geometry}>
        <meshStandardMaterial color={'#FF9470'} emissive={'#FF9470'} emissiveIntensity={2} toneMapped={false} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/window.glb')

export default Model_Window
