/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Model_Matress(props) {
  const { nodes, materials } = useGLTF('/models/matress.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.matress.geometry} material={materials.MatressMat} />
    </group>
  )
}

useGLTF.preload('/models/matress.glb')

export default Model_Matress
