/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, Html } from '@react-three/drei'

function Model_Frames(props) {
  const { nodes, materials } = useGLTF('/models/frames.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Cube007.geometry} material={materials.frameBrownMat} />
      <mesh castShadow receiveShadow geometry={nodes.Cube007_1.geometry} material={materials.white} />
      <mesh castShadow receiveShadow geometry={nodes.Cube007_2.geometry} material={materials.frameInnerMat} />

      <Html position={[-1.6, 1.8, -2.2]}>
        <div className='object-html-marker' onClick={() => props.onClick('frames')}>
          
        </div>
      </Html>
    </group>
  )
}

useGLTF.preload('/models/frames.glb')

export default Model_Frames
