/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Model_Room(props) {
  const { nodes, materials } = useGLTF('/models/room.glb')

  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Plane001.geometry} material={materials.brickwallWhite} />
      <mesh castShadow receiveShadow geometry={nodes.Plane001_1.geometry} material={materials.floorboards} />
    </group>
  )
}

useGLTF.preload('/models/room.glb')

export default Model_Room
